metadata:
  appversion: ${artifact.metadata.tag}

deployment:
  name: pmt-product-agreement-mgmt-api-ds
  replica_count: 1
  hpa:
    min_replicas: 1
    max_replicas: 2
    target_cpu_utilization_percentage: 80

containers:
  - name: pmt-product-agreement-mgmt-api
    image:
      name : ${artifact.metadata.image}
      pullPolicy: IfNotPresent
    ports:
      - container_port: 8080
        name: http
    k8s:
      resources:
        limits:
          cpu: 700m
          memory: 1Gi
        requests:
          cpu: 20m
          memory: 350Mi
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
        http:
          port: 8080
          path: /actuator/health/liveness
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 3
        http:
          port: 8080
          path: /actuator/health/readiness

